// Generated by https://quicktype.io

export interface Latitude57044746Longitude9955109GenerationtimeMS019502639770507812UTCOffsetSeconds3600TimezoneEuropeBerlinTimezoneAbbreviationGMT1Elevation370HourlyUnitsTimeIso8601Temperature2MCApparentTemperatureCRelativeHumidity2MPrecipitationMmSnowfallCMRainMmVisibilityMWindSpeed10MKMHWindDirection10MWeatherCodeWmoCodeIsDaySunshineDurationSCloudCoverCloudCover2MHourlyTime20260206T000020260206T010020260206T020020260206T030020260206T040020260206T050020260206T060020260206T070020260206T080020260206T090020260206T100020260206T110020260206T120020260206T130020260206T140020260206T150020260206T160020260206T170020260206T180020260206T190020260206T200020260206T210020260206T220020260206T2300Temperature2M181919202120191919182124242322191818191918171515ApparentTemperature808183828784818079788386898581797977787977747371RelativeHumidity2M919091919091929192929291919192929292929292929292Precipitation160110090100090100120130140110080150120120130130060030020020020010020010Snowfall056056049042042049056056056056042049056056056056035014007007007007007000Rain080030020040030030040050060030020080040040050050010010010010010000010010Visibility146000144000186000136000174000142000138000134000138000154000188000130000144000142000136000154000212000392000338000378000428000410000522000776000WindSpeed10M252252263248270263248245241238252245266245230234245234234238227223223216WindDirection10M626059555861586063635755626062656567666972727574WeatherCode737373737373737373737373737373737371717171717151IsDay000000000111111110000000SunshineDuration000000000000000000000000000000000000000000000000000000000000000000000000CloudCover100100100100100100100100100100100100100100100100100100100100100100100100CloudCover2M443434444335444321111110 {
    latitude:              number;
    longitude:             number;
    generationtime_ms:     number;
    utc_offset_seconds:    number;
    timezone:              string;
    timezone_abbreviation: string;
    elevation:             number;
    hourly_units:          HourlyUnits;
    hourly:                Hourly;
}

export interface Hourly {
    time:                 string[];
    temperature_2m:       number[];
    apparent_temperature: number[];
    relative_humidity_2m: number[];
    precipitation:        number[];
    snowfall:             number[];
    rain:                 number[];
    visibility:           number[];
    wind_speed_10m:       number[];
    wind_direction_10m:   number[];
    weather_code:         number[];
    is_day:               number[];
    sunshine_duration:    number[];
    cloud_cover:          number[];
    cloud_cover_2m:       number[];
}

export interface HourlyUnits {
    time:                 string;
    temperature_2m:       string;
    apparent_temperature: string;
    relative_humidity_2m: string;
    precipitation:        string;
    snowfall:             string;
    rain:                 string;
    visibility:           string;
    wind_speed_10m:       string;
    wind_direction_10m:   string;
    weather_code:         string;
    is_day:               string;
    sunshine_duration:    string;
    cloud_cover:          string;
    cloud_cover_2m:       string;
}
