// Generated by https://quicktype.io

export interface Latitude57044746Longitude9955109GenerationtimeMS023543834686279297UTCOffsetSeconds3600TimezoneEuropeBerlinTimezoneAbbreviationGMT1Elevation370DailyUnitsTimeIso8601WeatherCodeWmoCodeTemperature2MMaxCTemperature2MMinCWindSpeed10MMaxKMHWindDirection10MDominantSunriseIso8601SunsetIso8601DaylightDurationSPrecipitationSumMmRainSumMmSnowfallSumCMPrecipitationHoursHDailyTime202602062026020720260208WeatherCode73713Temperature2MMax150406Temperature2MMin241730WindSpeed10MMax270234205WindDirection10MDominant637485Sunrise20260206T080820260207T080620260208T0804Sunset20260206T165920260207T170120260208T1704DaylightDuration318605532128873239778PrecipitationSum2070190000RainSum760040000SnowfallSum917105000PrecipitationHours24017000 {
    latitude:              number;
    longitude:             number;
    generationtime_ms:     number;
    utc_offset_seconds:    number;
    timezone:              string;
    timezone_abbreviation: string;
    elevation:             number;
    daily_units:           DailyUnits;
    daily:                 Daily;
}

export interface Daily {
    time:                        Date[];
    weather_code:                number[];
    temperature_2m_max:          number[];
    temperature_2m_min:          number[];
    wind_speed_10m_max:          number[];
    wind_direction_10m_dominant: number[];
    sunrise:                     string[];
    sunset:                      string[];
    daylight_duration:           number[];
    precipitation_sum:           number[];
    rain_sum:                    number[];
    snowfall_sum:                number[];
    precipitation_hours:         number[];
}

export interface DailyUnits {
    time:                        string;
    weather_code:                string;
    temperature_2m_max:          string;
    temperature_2m_min:          string;
    wind_speed_10m_max:          string;
    wind_direction_10m_dominant: string;
    sunrise:                     string;
    sunset:                      string;
    daylight_duration:           string;
    precipitation_sum:           string;
    rain_sum:                    string;
    snowfall_sum:                string;
    precipitation_hours:         string;
}
